on:
  pull_request:
    paths:
      - .github/

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          show-progress: false
          sparse-checkout: '.github/'
      - uses: docker://rhysd/actionlint:1.7.7
        with:
          args: -color
